services:
  - type: web
    name: minio
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: admin123
      - key: MINIO_SERVER_URL
        value: https://pqrsd-hswa.onrender.com
      - key: MINIO_BROWSER_REDIRECT_URL
        value: https://pqrsd-hswa.onrender.com

    startCommand: >
      minio server /data --console-address ":9090" --address ":9000"
