services:
  - type: web
    name: minio
    env: docker
    plan: free
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 5
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: admin123
