services:
  - type: web
    name: minio
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: supersecretpassword
    startCommand: >
      minio server /data --console-address ":9090" --address ":9000"
